# -*- coding: utf-8 -*-
"""Weather text file.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Na98CyVNiln-OvDYTLN4w1ga_nrzttg4

import requests
#import os
from datetime import datetime

api_key = '5bcf8db0557df41e5e337306e4e35721'
location = input("Enter the city name: ")

complete_api_link = "https://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

#create variables to store and display data
temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

print ("-------------------------------------------------------------")
print ("Weather Stats for - {}  || {}".format(location.upper(), date_time))
print ("-------------------------------------------------------------")

print ("Current temperature is: {:.2f} deg C".format(temp_city))
print ("Current weather desc  :",weather_desc)
print ("Current Humidity      :",hmdt, '%')
print ("Current wind speed    :",wind_spd ,'kmph')

Enter the city name: madurai
-------------------------------------------------------------
Weather Stats for - MADURAI  || 23 Jun 2021 | 08:47:20 AM
-------------------------------------------------------------
Current temperature is: 36.01 deg C
Current weather desc  : scattered clouds
Current Humidity      : 41 %
Current wind speed    : 2.57 kmph

https://api.openweathermap.org/data/2.5/weather?q=madurai&appid=5bcf8db0557df41e5e337306e4e35721

{"coord":{"lon":78.1167,"lat":9.9333},"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"base":"stations","main":{"temp":310.16,"feels_like":313.99,"temp_min":310.16,"temp_max":310.16,"pressure":1006,"humidity":39},"visibility":7000,"wind":{"speed":2.57,"deg":300},"clouds":{"all":40},"dt":1624438084,"sys":{"type":1,"id":9216,"country":"IN","sunrise":1624408114,"sunset":1624453846},"timezone":19800,"id":1264521,"name":"Madurai","cod":200}
"""